// Isolated renderer integration checks; no personal records are read or written.
const { app, BrowserWindow, ipcMain } = require('electron');
const path = require('node:path');
const fs = require('node:fs');
const assert = require('node:assert/strict');
const G = require('../src/game');
const root = path.join(__dirname, '..');
let saved = G.defaultState();
saved.settings.sound = false;
saved.settings.focusMinutes = 30;
saved.settings.breakMinutes = 10;
app.setPath('userData', path.join(app.getPath('temp'), 'quest-breaks-check'));
const watchdog = setTimeout(() => app.exit(1), 30000);
app.whenReady().then(async () => {
  ipcMain.handle('state:load', () => saved);
  ipcMain.on('state:save', (_, state) => { saved = state; });
  ipcMain.handle('window:always-on-top', () => false);
  ipcMain.handle('update:auto', () => false);
  ipcMain.handle('update:get', () => ({ update: { status: 'none' } }));
  ipcMain.handle('notes:get', () => null);
  const win = new BrowserWindow({ width: 1000, height: 680, show: false,
    webPreferences: { preload: path.join(root, 'preload.js'), backgroundThrottling: false, offscreen: true } });
  const errors = [];
  win.webContents.on('console-message', e => { if (e.level === 'error') errors.push(e.message); });
  const ready = new Promise(resolve => ipcMain.once('renderer:ready', resolve));
  await win.loadFile(path.join(root, 'src/index.html'));
  await ready;
  const js = code => win.webContents.executeJavaScript(code, true);
  await js(`window.checkNow = Date.now(); Date.now = () => window.checkNow;
    document.getElementById('includeBreaks').click();
    document.getElementById('planMinutes').value = 50;
    document.getElementById('planMinutes').dispatchEvent(new Event('change'));`);
  assert.equal(await js(`document.getElementById('clock').textContent`), '50:00');
  assert.match(await js(`document.getElementById('breakRingColor').style.background`), /conic-gradient/);
  await new Promise(r => setTimeout(r, 1000));
  fs.mkdirSync(path.join(root, 'shots'), { recursive: true });
  fs.writeFileSync(path.join(root, 'shots/breaks.png'), (await win.webContents.capturePage()).toPNG());
  await js(`document.getElementById('btnGo').click(); window.checkNow += 35 * 60000;`);
  win.webContents.send('timer:resync');
  await new Promise(r => setTimeout(r, 300));
  assert.match(await js(`document.getElementById('fieldState').textContent`), /휴식하는 중/);
  await js(`document.getElementById('btnHold').click(); window.checkNow += 60000;`);
  assert.equal(await js(`document.getElementById('clock').textContent`), '15:00');
  await js(`document.getElementById('btnGo').click(); document.getElementById('btnPlus5').click();`);
  assert.equal(await js(`document.getElementById('clock').textContent`), '20:00');
  await js(`document.getElementById('btnStop').click();`);
  await new Promise(r => setTimeout(r, 100));
  assert.equal(saved.sessions[0].focusedSec, 1800);
  assert.equal(saved.sessions[0].breakSec, 300);
  assert.equal(saved.totalXp, 65);
  assert.equal(saved.sessions[0].completed, false);
  await js(`document.getElementById('btnGo').click(); window.checkNow += 50 * 60000;`);
  win.webContents.send('timer:elapsed');
  await new Promise(r => setTimeout(r, 100));
  assert.equal(saved.sessions[1].focusedSec, 2400);
  assert.equal(saved.sessions[1].breakSec, 600);
  assert.equal(saved.totalXp, 182);
  assert.equal(await js(`document.getElementById('settlement').open`), true);
  assert.equal(await js(`document.getElementById('settlementXp').textContent`), '+117');
  assert.equal(await js(`document.getElementById('settlementLevel').textContent`), 'Lv.1 → Lv.2');
  assert.equal(await js(`document.getElementById('settlementProgress').value`), 82);
  win.webContents.send('timer:elapsed');
  await new Promise(r => setTimeout(r, 500));
  assert.equal(saved.totalXp, 182);
  fs.writeFileSync(path.join(root, 'shots/settlement.png'), (await win.webContents.capturePage()).toPNG());
  await js(`document.getElementById('settlementClose').click();`);
  assert.equal(await js(`document.getElementById('settlement').open`), false);
  assert.equal(saved.sessions[1].completed, true);
  await js(`document.querySelector('[data-view="prefs"]').click();
    document.getElementById('prefFocusMin').value = 10;
    document.getElementById('prefFocusMin').dispatchEvent(new Event('change'));`);
  await new Promise(r => setTimeout(r, 100));
  assert.equal(saved.settings.focusMinutes, 10);
  assert.equal(saved.settings.includeBreaks, true);
  assert.deepEqual(errors, []);
  console.log('PASS: preview, break transition, pause/resume, extension, partial and full records, settings');
  clearTimeout(watchdog);
  app.exit(0);
}).catch(error => { console.error(error); app.exit(1); });
